#!/usr/bin/env bash
# PreToolUse guard: generated evidence is regenerated by `make fixtures`, never
# hand-edited; ROM images and third-party sources never enter the repository.
input=$(cat)
path=$(jq -r '.tool_input.file_path // .tool_input.notebook_path // empty' <<<"$input")
[ -z "$path" ] && exit 0
rel=${path#"$CLAUDE_PROJECT_DIR"/}
block() { echo "Blocked: $1 ($rel). See CLAUDE.md evidence rules." >&2; exit 2; }
case "$rel" in
  docs/archaeology/phase-0b/fixtures/MANIFEST.json)
    block "manifest is regenerated only after a reason is recorded in reconciliation.md" ;;
  docs/archaeology/phase-0b/fixtures/*.json|docs/archaeology/phase-0b/fixtures/*.txt)
    block "fixtures are extracted by 'make fixtures', not hand-edited" ;;
  src/core/include/daggorath/lexicon_tables.hpp)
    block "generated by tools/gen_lexicon_header.py" ;;
  third_party/*|vendor/*)
    block "third-party sources are reference-only and never edited or committed" ;;
  *.rom|*.ccc|*.bin|*.cas|*.dsk|captures/*)
    block "no ROM image or emulator capture enters the repository" ;;
esac
exit 0
