// GENERATED by tools/gen_lexicon_header.py from fixtures/tokens.json.
// Do not edit by hand. Ultimate source: TOKEN.ASM (5-bit packed token tables),
// decoded per EXPAND.ASM EXPANX/GETFIV.
#pragma once
#include <array>
#include <cstdint>
#include <string_view>

namespace dag {

struct TokenEntry {
    std::string_view word;
    std::uint8_t token_class;
    std::uint8_t index;   // token type == position in its table
};

inline constexpr std::array<TokenEntry, 15> kCmdTab{{
    {"ATTACK", 0, 0},  // T.ATTK
    {"CLIMB", 0, 1},  // T.CLIM
    {"DROP", 0, 2},  // T.DROP
    {"EXAMINE", 0, 3},  // T.EXAM
    {"GET", 0, 4},  // T.GET
    {"INCANT", 0, 5},  // T.INCN
    {"LOOK", 0, 6},  // T.LOOK
    {"MOVE", 0, 7},  // T.MOVE
    {"PULL", 0, 8},  // T.PULL
    {"REVEAL", 0, 9},  // T.REVE
    {"STOW", 0, 10},  // T.STOW
    {"TURN", 0, 11},  // T.TURN
    {"USE", 0, 12},  // T.USE
    {"ZLOAD", 0, 13},  // T.ZLOA
    {"ZSAVE", 0, 14},  // T.ZSAV
}};

inline constexpr std::array<TokenEntry, 6> kDirTab{{
    {"LEFT", 0, 0},  // T.LT
    {"RIGHT", 0, 1},  // T.RT
    {"BACK", 0, 2},  // T.BAK
    {"AROUND", 0, 3},  // T.AROU
    {"UP", 0, 4},  // T.UP
    {"DOWN", 0, 5},  // T.DN
}};

inline constexpr std::array<TokenEntry, 25> kAdjTab{{
    {"SUPREME", 1, 0},  // T.RN05
    {"JOULE", 1, 1},  // T.RN01
    {"ELVISH", 4, 2},  // T.SWO1
    {"MITHRIL", 3, 3},  // T.SHI1
    {"SEER", 2, 4},  // T.SCR1
    {"THEWS", 0, 5},  // T.FLA1
    {"RIME", 1, 6},  // T.RN03
    {"VISION", 2, 7},  // T.SCR2
    {"ABYE", 0, 8},  // T.FLA3
    {"HALE", 0, 9},  // T.FLA2
    {"SOLAR", 5, 10},  // T.TOR1
    {"BRONZE", 3, 11},  // T.SHI3
    {"VULCAN", 1, 12},  // T.RN02
    {"IRON", 4, 13},  // T.SWO2
    {"LUNAR", 5, 14},  // T.TOR2
    {"PINE", 5, 15},  // T.TOR4
    {"LEATHER", 3, 16},  // T.SHI4
    {"WOODEN", 4, 17},  // T.SWO3
    {"FINAL", 1, 18},  // T.RN15
    {"ENERGY", 1, 19},  // T.RN11
    {"ICE", 1, 20},  // T.RN13
    {"FIRE", 1, 21},  // T.RN12
    {"GOLD", 1, 22},  // T.RN20
    {"EMPTY", 0, 23},  // T.FLA4
    {"DEAD", 5, 24},  // T.TOR5
}};

inline constexpr std::array<TokenEntry, 6> kGenTab{{
    {"FLASK", 0, 0},  // T.FLA0
    {"RING", 1, 1},  // T.RIN0
    {"SCROLL", 2, 2},  // T.SCR0
    {"SHIELD", 3, 3},  // T.SHI0
    {"SWORD", 4, 4},  // T.SWO0
    {"TORCH", 5, 5},  // T.TOR0
}};

}  // namespace dag
