// GENERATED by tools/extract_sounds.py from fixtures/sounds.json.
// Do not edit by hand. Ultimate source: SOUNDS.ASM SNDTAB / SNDOBJ.
#pragma once
#include <array>
#include <cstdint>
#include <string_view>

namespace dag {

inline constexpr std::uint8_t kExtractedSndObj = 12;
inline constexpr std::array<std::string_view, 23> kSoundCueNames{{
    "A$SQK0", "A$RTL0", "A$ROR0", "A$BEP0", "A$KLK0", "A$ROR1", "A$RTL1", "A$KLK1", "A$PSHT", "A$ROR2", "A$SQK1", "A$SQK2", "A$FLAS", "A$RING", "A$SCRO", "A$SHIE", "A$SWOR", "A$TORC", "A$KLK2", "A$KLK3", "A$THUD", "A$EXP0", "A$EXP1"
}};

struct SoundCueRow {
    std::uint8_t index;
    std::string_view symbol;
    std::string_view generator;
};

inline constexpr std::array<SoundCueRow, 23> kSoundCueRows{{
    {0, "A$SQK0", "SQUEAK"},
    {1, "A$RTL0", "RATTLE"},
    {2, "A$ROR0", "GROWL"},
    {3, "A$BEP0", "BEOOP"},
    {4, "A$KLK0", "KLANK"},
    {5, "A$ROR1", "GRAWL"},
    {6, "A$RTL1", "PSSST"},
    {7, "A$KLK1", "KKLANK"},
    {8, "A$PSHT", "PSSHT"},
    {9, "A$ROR2", "SNARL"},
    {10, "A$SQK1", "BDLBDL"},
    {11, "A$SQK2", "BDLBDL"},
    {12, "A$FLAS", "GLUGLG"},
    {13, "A$RING", "PHASER"},
    {14, "A$SCRO", "WHOOP"},
    {15, "A$SHIE", "CLANG"},
    {16, "A$SWOR", "WHOOSH"},
    {17, "A$TORC", "CHUCK"},
    {18, "A$KLK2", "KLINK"},
    {19, "A$KLK3", "CLANK"},
    {20, "A$THUD", "THUD"},
    {21, "A$EXP0", "BANG"},
    {22, "A$EXP1", "KABOOM"},
}};

}  // namespace dag
