// GENERATED by tools/extract_text.py from the pinned listing.
// Do not edit by hand. Ultimate source: COMDAT.ASM, CD.ASM, PEXAM.ASM,
// STATUS.ASM, SWCHAR.ASM.
#pragma once
#include <array>
#include <cstdint>
#include <string_view>

namespace dag {

inline constexpr int kCentroidX = 128;
inline constexpr int kCentroidY = 76;
inline constexpr int kViewportScanlineEnd = 152;
inline constexpr int kStatusScanlineEnd = 160;
inline constexpr int kCommandScanlineEnd = 192;
inline constexpr int kExamineRows = 19;
inline constexpr int kExamineCols = 32;
inline constexpr int kStatusCharRows = 2;
inline constexpr int kCommandRows = 4;
inline constexpr int kMapCellScanlines = 6;

inline constexpr std::string_view kEmptyHand = "EMPTY";
inline constexpr std::string_view kExamRoom = "IN THIS ROOM";
inline constexpr std::string_view kExamCreature = "!CREATURE!";
inline constexpr std::string_view kExamBackpack = "BACKPACK";

inline constexpr std::array<std::uint8_t, 155> kSwcTab{{
    48, 0, 0, 0, 0, 49, 21, 24, 254, 49, 55, 163, 31, 70, 62, 51, 163, 8, 66, 46, 55, 163, 24, 198, 62, 55, 225, 15, 66, 31, 55, 225, 15, 66, 16, 51, 227, 8, 78, 47, 52, 99, 31, 198, 49, 51, 136, 66, 16, 142, 48, 66, 16, 134, 46, 52, 101, 76, 82, 81, 52, 33, 8, 66, 31, 52, 119, 90, 214, 49, 52, 99, 154, 206, 49, 51, 163, 24, 198, 46, 55, 163, 31, 66, 16, 51, 163, 24, 214, 77, 55, 163, 31, 82, 81, 51, 163, 7, 6, 46, 55, 234, 66, 16, 132, 52, 99, 24, 198, 46, 52, 99, 21, 40, 132, 52, 99, 26, 215, 113, 52, 98, 162, 42, 49, 52, 98, 162, 16, 132, 55, 194, 34, 34, 31, 49, 8, 66, 16, 4, 48, 0, 0, 0, 31, 51, 162, 19, 16, 4, 48, 0, 0, 0, 4
}};
inline constexpr std::array<std::uint8_t, 28> kSpcTab{{
    0, 0, 1, 1, 0, 0, 0, 0, 160, 240, 240, 224, 64, 0, 0, 1, 3, 3, 1, 0, 0, 0, 176, 248, 248, 240, 224, 64
}};

}  // namespace dag
