// GENERATED by tools/gen_vector_header.py from phase-6 vectors.json.
// Do not edit by hand. Ultimate source: VARC.ASM, VERT.ASM, VOBJ.ASM,
// D3.ASM, D4.ASM, VIEWER.ASM, VECTOR.ASM, SWCHAR.ASM, DTABAS.ASM, COMDAT.ASM.
#pragma once
#include <array>
#include <cstddef>
#include <cstdint>

namespace dag {

inline constexpr std::array<std::uint8_t, 1027> kVectorBlob{{
    16, 27, 38, 64, 114, 64, 136, 27, 254, 16, 229, 38, 192, 114, 192, 136,
    229, 254, 38, 64, 38, 192, 255, 114, 64, 114, 192, 254, 38, 29, 38, 64,
    114, 64, 114, 27, 255, 16, 27, 38, 64, 254, 38, 229, 38, 192, 114, 192,
    114, 229, 255, 16, 229, 38, 192, 254, 128, 40, 65, 40, 68, 56, 119, 56,
    255, 92, 48, 93, 52, 253, 0, 0, 128, 216, 65, 216, 68, 200, 119, 200,
    255, 92, 208, 93, 204, 253, 0, 9, 114, 108, 67, 108, 67, 148, 114, 148,
    255, 94, 126, 94, 130, 253, 0, 18, 128, 40, 66, 50, 117, 58, 254, 128,
    216, 66, 206, 117, 198, 254, 113, 108, 67, 128, 114, 148, 254, 100, 28, 252,
    68, 46, 66, 76, 0, 254, 100, 228, 252, 76, 34, 78, 68, 0, 254, 0,
    219, 0, 151, 0, 247, 0, 157, 251, 0, 163, 253, 0, 219, 251, 0, 163,
    253, 0, 247, 24, 116, 128, 116, 255, 24, 140, 128, 140, 255, 28, 116, 28,
    140, 255, 40, 116, 40, 140, 255, 52, 116, 52, 140, 255, 64, 116, 64, 140,
    255, 76, 116, 76, 140, 255, 88, 116, 88, 140, 255, 100, 116, 100, 140, 255,
    112, 116, 112, 140, 255, 123, 116, 123, 140, 255, 250, 34, 100, 24, 92, 24,
    164, 34, 156, 34, 100, 24, 100, 255, 34, 156, 24, 156, 255, 28, 47, 28,
    96, 255, 28, 161, 28, 210, 254, 118, 100, 128, 92, 128, 164, 118, 156, 118,
    100, 128, 100, 255, 118, 156, 128, 156, 255, 28, 47, 28, 210, 254, 134, 172,
    128, 192, 122, 186, 128, 168, 252, 62, 4, 0, 254, 118, 60, 252, 247, 255,
    42, 0, 254, 114, 80, 124, 100, 255, 118, 82, 114, 86, 254, 110, 162, 252,
    81, 14, 177, 0, 254, 122, 60, 252, 17, 31, 255, 241, 0, 254, 118, 194,
    252, 31, 52, 241, 220, 0, 254, 104, 98, 252, 215, 212, 20, 18, 48, 29,
    13, 253, 41, 0, 253, 1, 104, 104, 98, 94, 124, 96, 126, 106, 100, 255,
    102, 132, 92, 114, 102, 118, 110, 114, 102, 132, 252, 2, 86, 86, 23, 238,
    2, 234, 187, 187, 234, 234, 0, 78, 92, 252, 194, 81, 62, 207, 252, 66,
    19, 0, 106, 90, 252, 30, 17, 243, 98, 57, 226, 12, 228, 138, 226, 0,
    86, 84, 252, 84, 101, 46, 202, 186, 161, 212, 238, 18, 210, 19, 225, 32,
    246, 36, 114, 88, 238, 197, 190, 0, 254, 80, 124, 94, 114, 110, 120, 132,
    112, 104, 78, 132, 48, 68, 72, 84, 32, 22, 88, 52, 114, 92, 128, 52,
    142, 22, 168, 88, 224, 68, 184, 132, 208, 112, 178, 132, 144, 110, 136, 94,
    142, 80, 132, 255, 132, 112, 252, 197, 146, 190, 195, 67, 94, 114, 69, 0,
    82, 122, 252, 120, 233, 141, 236, 51, 12, 36, 114, 71, 231, 0, 22, 168,
    252, 45, 194, 61, 48, 75, 75, 237, 178, 157, 113, 61, 221, 145, 125, 82,
    99, 163, 45, 237, 45, 203, 203, 208, 221, 66, 237, 0, 254, 62, 68, 68,
    88, 56, 100, 255, 74, 90, 70, 74, 252, 51, 245, 245, 193, 90, 98, 14,
    0, 100, 80, 252, 179, 23, 52, 235, 10, 61, 0, 254, 124, 160, 252, 194,
    34, 228, 36, 44, 236, 4, 4, 226, 66, 0, 124, 168, 252, 193, 33, 18,
    242, 225, 65, 0, 254, 112, 74, 252, 224, 238, 44, 66, 20, 20, 32, 12,
    204, 34, 12, 34, 0, 124, 90, 252, 224, 12, 44, 32, 4, 0, 254, 82,
    130, 252, 40, 125, 95, 80, 91, 245, 47, 213, 23, 23, 243, 34, 225, 20,
    221, 143, 141, 219, 236, 0, 86, 130, 252, 51, 49, 27, 145, 59, 95, 245,
    0, 108, 116, 114, 118, 120, 144, 254, 34, 124, 252, 4, 31, 14, 255, 0,
    80, 142, 64, 136, 46, 146, 64, 156, 82, 140, 76, 136, 64, 146, 58, 140,
    253, 2, 185, 30, 126, 252, 80, 15, 224, 0, 44, 150, 52, 166, 76, 164,
    92, 150, 76, 136, 52, 134, 44, 150, 255, 80, 140, 128, 152, 132, 160, 132,
    144, 126, 144, 84, 130, 255, 84, 126, 126, 110, 132, 110, 132, 92, 128, 102,
    80, 116, 255, 80, 140, 252, 58, 217, 131, 222, 173, 230, 161, 226, 34, 97,
    38, 234, 32, 61, 221, 224, 0, 52, 128, 20, 128, 252, 14, 33, 2, 225,
    14, 0, 74, 102, 252, 224, 2, 208, 8, 48, 2, 32, 1, 48, 2, 208,
    1, 135, 0, 46, 110, 64, 102, 64, 100, 30, 102, 20, 98, 30, 94, 64,
    96, 64, 98, 20, 98, 254, 46, 98, 252, 33, 47, 45, 253, 206, 194, 242,
    18, 15, 30, 63, 33, 18, 227, 224, 0, 104, 154, 252, 33, 47, 45, 253,
    206, 194, 242, 18, 15, 30, 63, 34, 18, 226, 224, 0, 253, 3, 107, 40,
    86, 64, 92, 42, 100, 54, 82, 56, 104, 40, 86, 255, 66, 140, 252, 112,
    173, 53, 27, 179, 0, 96, 146, 120, 148, 100, 136, 106, 154, 116, 138, 96,
    146, 255, 80, 116, 252, 83, 236, 228, 77, 176, 0, 64, 124, 252, 78, 192,
    123, 156, 212, 228, 225, 225, 221, 28, 150, 3, 0, 28, 130, 252, 3, 69,
    113, 218, 30, 17, 225, 0, 48, 134, 54, 142, 116, 164, 132, 132, 130, 118,
    120, 94, 90, 110, 132, 132, 72, 106, 255, 64, 102, 252, 31, 189, 241, 83,
    0, 66, 102, 252, 30, 50, 17, 115, 0, 88, 112, 72, 120, 255, 62, 132,
    20, 128, 52, 122, 64, 122, 60, 124, 114, 128, 80, 130, 68, 130, 62, 132,
    255, 40, 130, 252, 255, 30, 17, 242, 63, 32, 15, 192, 255, 49, 0, 254,
    132, 130, 112, 122, 92, 124, 94, 126, 94, 130, 92, 132, 112, 130, 128, 140,
    132, 136, 132, 114, 120, 108, 106, 118, 120, 112, 124, 116, 124, 126, 255, 100,
    120, 252, 224, 226, 238, 224, 241, 34, 238, 6, 46, 226, 17, 32, 46, 34,
    32, 0, 254,
}};

inline constexpr std::size_t kVec_LWALL = 0;
inline constexpr std::size_t kVec_RWALL = 9;
inline constexpr std::size_t kVec_FWALL = 18;
inline constexpr std::size_t kVec_LPASAG = 28;
inline constexpr std::size_t kVec_RPASAG = 42;
inline constexpr std::size_t kVec_FPASAG = 55;
inline constexpr std::size_t kVec_LDOOR = 56;
inline constexpr std::size_t kVec_RDOOR = 72;
inline constexpr std::size_t kVec_FDOOR = 88;
inline constexpr std::size_t kVec_LSDOOR = 104;
inline constexpr std::size_t kVec_RSDOOR = 111;
inline constexpr std::size_t kVec_FSDOOR = 118;
inline constexpr std::size_t kVec_LPEEK = 125;
inline constexpr std::size_t kVec_RPEEK = 134;
inline constexpr std::size_t kVec_FWDVER = 143;
inline constexpr std::size_t kVec_FLUP = 151;
inline constexpr std::size_t kVec_FLDN = 157;
inline constexpr std::size_t kVec_LADDER = 163;
inline constexpr std::size_t kVec_HOLEUP = 219;
inline constexpr std::size_t kVec_HOLEDN = 247;
inline constexpr std::size_t kVec_CELINE = 265;
inline constexpr std::size_t kVec_VNULL = 269;
inline constexpr std::size_t kVec_FSHIEL = 270;
inline constexpr std::size_t kVec_FTORCH = 283;
inline constexpr std::size_t kVec_FSWORD = 291;
inline constexpr std::size_t kVec_FFLASK = 301;
inline constexpr std::size_t kVec_FRING = 309;
inline constexpr std::size_t kVec_FSCROL = 318;
inline constexpr std::size_t kVec_SGINT1 = 327;
inline constexpr std::size_t kVec_SGINT2 = 343;
inline constexpr std::size_t kVec_SGIANT = 360;
inline constexpr std::size_t kVec_BALROG = 425;
inline constexpr std::size_t kVec_WRAITH = 525;
inline constexpr std::size_t kVec_SPIDER = 556;
inline constexpr std::size_t kVec_SCORP = 581;
inline constexpr std::size_t kVec_BLOB = 607;
inline constexpr std::size_t kVec_KNIGT1 = 648;
inline constexpr std::size_t kVec_KNIGT2 = 675;
inline constexpr std::size_t kVec_KNIGHT = 697;
inline constexpr std::size_t kVec_WIZ1 = 790;
inline constexpr std::size_t kVec_WIZ2 = 831;
inline constexpr std::size_t kVec_WIZ0 = 875;
inline constexpr std::size_t kVec_VIPER = 976;

inline constexpr std::array<int, 10> kNorscl{{
    200, 128, 80, 50, 31, 20, 12, 8, 4, 2}};
inline constexpr std::array<int, 10> kHlfscl{{
    255, 156, 100, 65, 40, 26, 16, 10, 6, 3}};
inline constexpr std::array<int, 10> kBakscl{{
    156, 100, 65, 40, 26, 16, 10, 6, 3, 1}};
inline constexpr std::array<std::uint8_t, 8> kBitmsk{{
    128, 64, 32, 16, 8, 4, 2, 1}};
inline constexpr int kCentroidX = 128;
inline constexpr int kCentroidY = 76;

struct FlaEntry { int rel; std::size_t lists[4]; };
inline constexpr std::array<FlaEntry, 3> kFlaTab{{
    {3, {kVec_LPASAG, kVec_LDOOR, kVec_LSDOOR, kVec_LWALL}},
    {0, {kVec_FPASAG, kVec_FDOOR, kVec_FSDOOR, kVec_FWALL}},
    {1, {kVec_RPASAG, kVec_RDOOR, kVec_RSDOOR, kVec_RWALL}},
}};
inline constexpr std::array<std::size_t, 6> kFwdObj{{
    kVec_FFLASK, kVec_FRING, kVec_FSCROL, kVec_FSHIEL, kVec_FSWORD, kVec_FTORCH}};
inline constexpr std::array<std::size_t, 12> kFwdCre{{
    kVec_SPIDER, kVec_VIPER, kVec_SGINT1, kVec_BLOB, kVec_KNIGT1, kVec_SGINT2, kVec_SCORP, kVec_KNIGT2, kVec_WRAITH, kVec_BALROG, kVec_WIZ0, kVec_WIZ1}};
inline constexpr std::array<std::size_t, 4> kFwdVer{{
    kVec_HOLEUP, kVec_FLUP, kVec_HOLEDN, kVec_FLDN}};
inline constexpr std::size_t kCeline = kVec_CELINE;
inline constexpr std::size_t kLpeek = kVec_LPEEK;
inline constexpr std::size_t kRpeek = kVec_RPEEK;

}  // namespace dag
