#!/usr/bin/env python3
"""Extract SOUNDS.ASM cue dispatch and generator parameters.

Usage: extract_sounds.py <asm-dir> <out-dir> [header-path]

Every value is read from the pinned listing. Hashes are computed, never typed.
"""
import hashlib
import json
import os
import re
import sys


def read(asmdir, name):
    with open(os.path.join(asmdir, name), "r", errors="replace") as f:
        return f.read()


def parse_sndtab(text):
    cues = []
    sndobj = None
    sndobj_line = 0
    for i, line in enumerate(text.splitlines(), 1):
        m = re.match(r"^SNDOBJ\s+EQU\s+(\d+)", line)
        if m:
            sndobj = int(m.group(1))
            sndobj_line = i
        m = re.match(r"^\s+SND\s+([A-Z0-9]+),([A-Z0-9]+)", line)
        if m:
            cues.append({
                "index": len(cues),
                "symbol": "A$" + m.group(1),
                "generator": m.group(2),
                "source": f"SOUNDS.ASM:{i}",
            })
    if sndobj is None:
        raise SystemExit("SNDOBJ not found")
    if len(cues) != 23:
        raise SystemExit(f"SNDTAB has {len(cues)} entries, expected 23")
    return cues, sndobj, sndobj_line


def parse_immediates(text, label):
    """Immediates between `label` and the next unindented code label."""
    lines = text.splitlines()
    start = None
    for i, line in enumerate(lines):
        if re.match(r"^%s\b" % re.escape(label), line):
            start = i
            break
    if start is None:
        return None
    body = []
    for j in range(start, len(lines)):
        line = lines[j]
        if j > start and re.match(r"^[A-Z][A-Z0-9]*\s", line):
            break
        body.append((start + j - start + 1, line))
    immediates = []
    for lineno, line in body:
        code = line.split(";", 1)[0]
        comment = line.split(";", 1)[1].strip() if ";" in line else ""
        for pat, base in (
            (r"LDA\s+#(\d+)", 10),
            (r"LDB\s+#(\d+)", 10),
            (r"LDX\s+#\$([0-9A-Fa-f]+)", 16),
            (r"LDY\s+#\$([0-9A-Fa-f]+)", 16),
            (r"FCB\s+\$([0-9A-Fa-f]+)", 16),
            (r"FDB\s+\$([0-9A-Fa-f]+)", 16),
        ):
            m = re.search(pat, code)
            if m:
                immediates.append({
                    "line": lineno,
                    "value": int(m.group(1), base),
                    "hex": hex(int(m.group(1), base)),
                    "comment": comment,
                    "insn": code.strip(),
                })
                break
    loop = None
    for imm in immediates:
        if "iteration count" in imm["comment"] or "whoop count" in imm["comment"] \
                or "rattle count" in imm["comment"]:
            loop = imm["value"]
            break
    return {"label": label, "source": f"SOUNDS.ASM:{start + 1}", "immediates": immediates,
            "loop_count": loop}


def parse_fdb_block(text, label, filename):
    lines = text.splitlines()
    start = None
    for i, line in enumerate(lines):
        if re.match(r"^%s\b" % re.escape(label), line):
            start = i
            break
    if start is None:
        raise SystemExit(f"{label} not in {filename}")
    words = []
    for j in range(start, len(lines)):
        line = lines[j]
        if j > start and re.match(r"^[A-Z][A-Z0-9]*\s", line):
            break
        m = re.search(r"FDB\s+\$([0-9A-Fa-f]+)", line.split(";", 1)[0])
        if m:
            words.append({"line": j + 1, "value": int(m.group(1), 16)})
    return {"label": label, "source": f"{filename}:{start + 1}", "words": words}


def snoise_note(text):
    start = None
    for i, line in enumerate(text.splitlines(), 1):
        if re.match(r"^SNOISE\b", line):
            start = i
            break
    if start is None:
        raise SystemExit("SNOISE not found")
    return {
        "source": f"SOUNDS.ASM:{start}",
        "updates": "SNDRND",
        "reads_seed": False,
        "writes_seed": False,
        "method": "LDD SNDRND; multiply by five (two left shifts plus add); INCB; STD SNDRND",
    }


def write_header(path, cues, sndobj):
    names = ", ".join(f'"{c["symbol"]}"' for c in cues)
    loops = []
    for c in cues:
        loops.append("    {%d, \"%s\", \"%s\"}," % (
            c["index"], c["symbol"], c["generator"]))
    body = f"""// GENERATED by tools/extract_sounds.py from fixtures/sounds.json.
// Do not edit by hand. Ultimate source: SOUNDS.ASM SNDTAB / SNDOBJ.
#pragma once
#include <array>
#include <cstdint>
#include <string_view>

namespace dag {{

inline constexpr std::uint8_t kExtractedSndObj = {sndobj};
inline constexpr std::array<std::string_view, {len(cues)}> kSoundCueNames{{{{
    {names}
}}}};

struct SoundCueRow {{
    std::uint8_t index;
    std::string_view symbol;
    std::string_view generator;
}};

inline constexpr std::array<SoundCueRow, {len(cues)}> kSoundCueRows{{{{
{chr(10).join(loops)}
}}}};

}}  // namespace dag
"""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        f.write(body)
    print(f"wrote {path}")


def patch_manifest(outdir, name, blob):
    manifest_path = os.path.join(outdir, "MANIFEST.json")
    with open(manifest_path) as f:
        manifest = json.load(f)
    entry = {
        "file": name,
        "sha256": hashlib.sha256(blob).hexdigest(),
        "bytes": len(blob),
    }
    manifest["fixtures"] = [e for e in manifest["fixtures"] if e["file"] != name]
    manifest["fixtures"].append(entry)
    manifest["fixtures"].sort(key=lambda e: e["file"])
    with open(manifest_path, "w") as f:
        json.dump(manifest, f, indent=2)
        f.write("\n")


def main():
    if len(sys.argv) < 3:
        print(__doc__.strip())
        return 2
    asmdir, outdir = sys.argv[1], sys.argv[2]
    header = sys.argv[3] if len(sys.argv) > 3 else None
    sounds = read(asmdir, "SOUNDS.ASM")
    swchar = read(asmdir, "SWCHAR.ASM")
    cues, sndobj, sndobj_line = parse_sndtab(sounds)
    generators = {}
    for c in cues:
        g = c["generator"]
        if g not in generators:
            parsed = parse_immediates(sounds, g)
            if parsed is None:
                raise SystemExit(f"generator {g} not found")
            generators[g] = parsed
    doc = {
        "description": "SOUNDS dispatch table, object-cue base, generator immediates, SNOISE",
        "source": "SOUNDS.ASM SNDTAB/SNDOBJ/SOUNDX/SOUNDI/SNOISE; SWCHAR.ASM THUDD/BANGD",
        "extraction_method":
            "SND macro arguments and SNDOBJ EQU read verbatim. Generator immediates "
            "are the LDA/LDB/LDX/LDY/FCB/FDB literals between a generator label and "
            "the next unindented label. THUDD and BANGD FDB words come from SWCHAR.ASM. "
            "SNOISE is recorded as operating on SNDRND only.",
        "sndobj": {"value": sndobj, "source": f"SOUNDS.ASM:{sndobj_line}"},
        "cues": cues,
        "generators": generators,
        "tables": {
            "THUDD": parse_fdb_block(swchar, "THUDD", "SWCHAR.ASM"),
            "BANGD": parse_fdb_block(swchar, "BANGD", "SWCHAR.ASM"),
        },
        "snoise": snoise_note(sounds),
        "volume": {
            "isound": {"B": 255, "source": "SOUNDS.ASM:19 SOUNDI LDB #$FF"},
            "same_cell": {"B": 255, "source": "CRETUR.ASM:78 CMOV20 LDB #$FF"},
            "range": {
                "formula": "B = ~(T0 * 31)  (8-bit)",
                "source": "CRETUR.ASM:355-358 CWLK20",
            },
        },
    }
    blob = json.dumps(doc, indent=2, sort_keys=False).encode() + b"\n"
    os.makedirs(outdir, exist_ok=True)
    path = os.path.join(outdir, "sounds.json")
    with open(path, "wb") as f:
        f.write(blob)
    patch_manifest(outdir, "sounds.json", blob)
    print(f"wrote {path} sha256={hashlib.sha256(blob).hexdigest()} bytes={len(blob)}")
    if header:
        write_header(header, cues, sndobj)
    return 0


if __name__ == "__main__":
    sys.exit(main())
