#!/usr/bin/env python3
"""Generate reference/include/daggorath/lexicon_tables.hpp from tokens.json.

The C++ core never hand-types the lexicon: this header is generated from the
fixtures, which are themselves decoded from TOKEN.ASM.
"""
import json
import sys

fixtures, out_path = sys.argv[1], sys.argv[2]
d = json.load(open(fixtures))["tables"]

def emit(name, entries):
    lines = [f"inline constexpr std::array<TokenEntry, {len(entries)}> {name}{{{{"]
    for e in entries:
        lines.append(f'    {{"{e["word"]}", {e["class"]}, {e["index"]}}},'
                     f'  // {e["symbol"]}')
    lines.append("}};")
    return "\n".join(lines)

body = "\n\n".join(emit(n, d[t]) for n, t in
                   (("kCmdTab", "CMDTAB"), ("kDirTab", "DIRTAB"),
                    ("kAdjTab", "ADJTAB"), ("kGenTab", "GENTAB")))

with open(out_path, "w") as f:
    f.write(f"""// GENERATED by tools/gen_lexicon_header.py from fixtures/tokens.json.
// Do not edit by hand. Ultimate source: TOKEN.ASM (5-bit packed token tables),
// decoded per EXPAND.ASM EXPANX/GETFIV.
#pragma once
#include <array>
#include <cstdint>
#include <string_view>

namespace dag {{

struct TokenEntry {{
    std::string_view word;
    std::uint8_t token_class;
    std::uint8_t index;   // token type == position in its table
}};

{body}

}}  // namespace dag
""")
print(f"wrote {out_path}")
