#!/usr/bin/env python3
"""Generate src/presentation/include/daggorath/vector_tables.hpp from vectors.json."""
import json
import sys


def chunks(seq, n):
    for i in range(0, len(seq), n):
        yield seq[i:i + n]


def main():
    if len(sys.argv) != 3:
        print("usage: gen_vector_header.py vectors.json vector_tables.hpp")
        return 2
    doc = json.load(open(sys.argv[1]))
    blob = doc["blob"]
    symbols = doc["symbols"]
    lines = [
        "// GENERATED by tools/gen_vector_header.py from phase-6 vectors.json.",
        "// Do not edit by hand. Ultimate source: VARC.ASM, VERT.ASM, VOBJ.ASM,",
        "// D3.ASM, D4.ASM, VIEWER.ASM, VECTOR.ASM, SWCHAR.ASM, DTABAS.ASM, COMDAT.ASM.",
        "#pragma once",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace dag {",
        "",
        f"inline constexpr std::array<std::uint8_t, {len(blob)}> kVectorBlob{{{{",
    ]
    for group in chunks(blob, 16):
        lines.append("    " + ", ".join(str(b) for b in group) + ",")
    lines.append("}};")
    lines.append("")
    for name, off in sorted(symbols.items(), key=lambda kv: kv[1]):
        ident = "kVec_" + name.replace("$", "_")
        lines.append(f"inline constexpr std::size_t {ident} = {off};")
    lines.append("")
    lines.append("inline constexpr std::array<int, 10> kNorscl{{")
    lines.append("    " + ", ".join(str(v) for v in doc["norscl"]) + "}};")
    lines.append("inline constexpr std::array<int, 10> kHlfscl{{")
    lines.append("    " + ", ".join(str(v) for v in doc["hlfscl"]) + "}};")
    lines.append("inline constexpr std::array<int, 10> kBakscl{{")
    lines.append("    " + ", ".join(str(v) for v in doc["bakscl"]) + "}};")
    lines.append("inline constexpr std::array<std::uint8_t, 8> kBitmsk{{")
    lines.append("    " + ", ".join(str(v) for v in doc["bitmsk"]) + "}};")
    lines.append(f"inline constexpr int kCentroidX = {doc['centroid_x']};")
    lines.append(f"inline constexpr int kCentroidY = {doc['centroid_y']};")
    lines.append("")
    lines.append("struct FlaEntry { int rel; std::size_t lists[4]; };")
    lines.append("inline constexpr std::array<FlaEntry, 3> kFlaTab{{")
    for e in doc["flatab"]:
        offs = ", ".join("kVec_" + n for n in e["lists"])
        lines.append(f"    {{{e['rel']}, {{{offs}}}}},")
    lines.append("}};")
    lines.append("inline constexpr std::array<std::size_t, 6> kFwdObj{{")
    lines.append("    " + ", ".join("kVec_" + n for n in doc["fwdobj"]) + "}};")
    lines.append("inline constexpr std::array<std::size_t, 12> kFwdCre{{")
    lines.append("    " + ", ".join("kVec_" + n for n in doc["fwdcre"]) + "}};")
    lines.append("inline constexpr std::array<std::size_t, 4> kFwdVer{{")
    lines.append("    " + ", ".join("kVec_" + n for n in doc["fwdver"]) + "}};")
    lines.append(f"inline constexpr std::size_t kCeline = kVec_{doc['celine']};")
    lines.append(f"inline constexpr std::size_t kLpeek = kVec_{doc['lpeek']};")
    lines.append(f"inline constexpr std::size_t kRpeek = kVec_{doc['rpeek']};")
    lines.append("")
    lines.append("}  // namespace dag")
    lines.append("")
    with open(sys.argv[2], "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
    print("wrote", sys.argv[2])
    return 0


if __name__ == "__main__":
    sys.exit(main())
